

# Logger Config
logging:
    level:
      com.neo: debug
#mysql
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?useSSL=false
        username: root
        password: 123456